// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_CH8Iei0PfKdp28DA1gMUzu3JP2Cna1A',
    appId: '1:256484787693:android:9842a0b29c1d74b46953e4',
    messagingSenderId: '256484787693',
    projectId: 'ordentrabajoar',
    storageBucket: 'ordentrabajoar.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWYNVXwjrkjW0khlpVJUmnVDKkat58mWA',
    appId: '1:256484787693:ios:90bfb3f35c1bbf8e6953e4',
    messagingSenderId: '256484787693',
    projectId: 'ordentrabajoar',
    storageBucket: 'ordentrabajoar.appspot.com',
    androidClientId: '256484787693-3c8tbdmvvgi42cuelbavu84f3l2i65io.apps.googleusercontent.com',
    iosClientId: '256484787693-tm5ju2rf4e5j41enqa6ndludgnu2umkl.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoApp.RunnerTests',
  );

}